[package]
name = "substreams-solana-address-lookup-table"
version = "0.1.0"
description = "Address lookup table Substreams"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bs58 = "0.4.0"
wasm-bindgen = "0.2.79"
prost = "0.11.0"
prost-types = "0.11.0"
substreams = "^0.5.0"
#substreams-solana = "^0.10.0"
substreams-solana = { git= "https://github.com/streamingfast/substreams-solana.git", branch="feature/owned" }
thiserror = "1.0.25"

[build-dependencies]
prost-build = "0.11.0"
anyhow = "1"
#substreams-solana = "^0.10.0"
substreams-solana = { git= "https://github.com/streamingfast/substreams-solana.git", branch="feature/owned" }

[target.wasm32-unknown-unknown.dependencies]
getrandom = { version = "0.2", features = ["custom"] }
